spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://aalevenegass_db_user:zMiW8Yqv6PB9zicG@eva-u2-spring.cztkeef.mongodb.net/?appName=eva-u2-spring
spring.data.mongodb.database=discografia-db
